### ISSUE TITLE
[FEATURE] Consider adding another way of displaying the active effects

### ISSUE THREAD

**Issue by mech-tools** [ElfFriend-DnD/foundryvtt-temp-effects-as-statuses#1]
Hey,

First of: great tools suite you are developing for 5e. I really like your low automation approach, but still have it a little so everything runs faster.
I'm installing and testing all of them! Prepare to receive feature request or bug reports :)

Also, having a list of all your modules that runs smoothly with one another would be great.
So far, I got:

- https://github.com/ElfFriend-DnD/foundryvtt-temp-effects-as-statuses
- https://github.com/ElfFriend-DnD/foundryvtt-item-effects-to-chat-5e
- https://github.com/ElfFriend-DnD/foundryvtt-attack-roll-check-5e
- https://github.com/ElfFriend-DnD/foundryvtt-auto-roll-npc-save-5e
- https://github.com/ElfFriend-DnD/foundryvtt-compact-roll-card-5e
- https://github.com/ElfFriend-DnD/foundryvtt-more-hooks-5e
- https://github.com/ElfFriend-DnD/foundryvtt-simple-effect-sheet-5e (developing stage?)

Now for the feature request.
Pathfinder uses a clever way to display the active effects. I created a ticket on CUB at some point, but never developed: https://github.com/death-save/combat-utility-belt/issues/563

In fact, I think this is more handy to just:
- Select a token to see the effect in the top right corner of the screen
- Right-click on an effect to "kill it"

Than the current state of this module:
- Select a token
- Right-click it
- Click on the status effects icon
- Find the status effect
- Click on it

**Comment by akrigline** [comment]
Thanks for all the feedback! It's good to see someone else enjoying this work.

(Simple effect sheet is very wip yeah, don't use that yet)

I'm not interested in deviating from the core token HUD behavior here, though I agree that's a neat behavior.
